# This is a basic workflow to help you get started with Actions

name: Sync-Dev

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  vindrogames_sync_dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    

    - name: Auth and sync data
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SYNC_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SYNC_SECRET_ACCESS_KEY }}
        AWS_EC2_METADATA_DISABLED: true
      run: aws s3 sync html/ s3://zeneke-aws5-public-vindrogames